### ISSUE TITLE
Unable to load audio files, browser requests "0.js"

### ISSUE THREAD

**Issue by lewispollard** [joshwcomeau/use-sound#45]
I've tried both importing the mp3s via webpack, and referring to them by public URL. I've verified I can access the public files via a browser directly, and webpack seems to pick up the mp3s via the other method without issue.

However when using the hook, eg:
`import sfxApplauseLight from "../audio/applause-lite.mp3";`
...
`const [sfxOneLineWon, sfxOneLineWonData] = useSound(sfxApplauseLight);`

OR 

`const [sfxOneLineWon, sfxOneLineWonData] = useSound('/audio/applause-lite.mp3');`

I get the error:

```
app.js:106 Uncaught (in promise) ChunkLoadError: Loading chunk 0 failed.
(error: http://localhost:3000/game/7/0.js)
    at Function.requireEnsure [as e] (http://localhost:3000/app.js:106:26)
    at eval (webpack-internal:///./node_modules/use-sound/dist/use-sound.esm.js:87:25)
    at commitHookEffectListMount (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19731:26)
    at commitPassiveHookEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19769:11)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22853:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11039:10)
```

It seems like no matter what I pass as the argument to useSound, url or import, it seems to try to request "0.js" which fails (since it doesn't exist, and also it gets an unauthorised response).

Unsure what I'm missing here but it must be something!

**Comment by lewispollard** [comment]
Ok, having read the README more thoroughly I see that the Howler script is requested async, which webpack was building down to "0.js" and putting into the public folder. If I request that directly in the browser, it loads; however for some reason the hook seems to be requesting it using a relative path, which is causing the issue.

**Comment by lewispollard** [comment]
Closed - the issue was with my webpack config. No publicPath set - oddly this worked with express static serving for images, but not for .js files

**Comment by atinder** [comment]
@lewispollard I am facing the same issue.
How do you set the `publicPath` for it to work correctly?

**Comment by lewispollard** [comment]
I'm afraid I don't know anything about rails, but I just added:
```
  output: {
    path: path.resolve(__dirname, "../public/"),
    publicPath: "/",
    filename: "[name].js",
  },
```

To my clientside webpack config, and it worked fine then
